rm -rf "../synth/__projnav" 
rm -rf "../synth/xst" 
rm -rf "../synth/_ngo" 

rm -rf tmp 
rm -rf _xmsgs 
rm -rf vio_sync_out32_xdb 
rm -rf vio_async_in96_xdb 
rm -rf vio_async_in100_xdb 
rm -rf vio_async_in192_xdb 
rm -rf icon4_xdb 

rm -rf xst 
rm -rf xlnx_auto_0_xdb 

rm -rf coregen.log 
rm -rf vio_sync_out32.asy 
rm -rf vio_sync_out32.cdc 
rm -rf vio_sync_out32.gise 
rm -rf vio_sync_out32.ise 
rm -rf vio_sync_out32.ncf 
rm -rf vio_sync_out32.ngc 
rm -rf vio_sync_out32.xco 
rm -rf vio_sync_out32.xise 
rm -rf vio_sync_out32_flist.txt 
rm -rf vio_sync_out32_readme.txt 
rm -rf vio_sync_out32_xmdf.tcl 

rm -rf vio_async_in100.asy 
rm -rf vio_async_in100.cdc 
rm -rf vio_async_in100.gise 
rm -rf vio_async_in100.ise 
rm -rf vio_async_in100.ncf 
rm -rf vio_async_in100.ngc 
rm -rf vio_async_in100.xco 
rm -rf vio_async_in100.xise 
rm -rf vio_async_in100_flist.txt 
rm -rf vio_async_in100_readme.txt 
rm -rf vio_async_in100_xmdf.tcl 


rm -rf vio_async_in192.asy 
rm -rf vio_async_in192.cdc 
rm -rf vio_async_in192.gise 
rm -rf vio_async_in192.ise 
rm -rf vio_async_in192.ncf 
rm -rf vio_async_in192.ngc 
rm -rf vio_async_in192.xco 
rm -rf vio_async_in192.xise 
rm -rf vio_async_in192_flist.txt 
rm -rf vio_async_in192_readme.txt 
rm -rf vio_async_in192_xmdf.tcl 

rm -rf vio_async_in96.asy 
rm -rf vio_async_in96.cdc 
rm -rf vio_async_in96.gise 
rm -rf vio_async_in96.ise 
rm -rf vio_async_in96.ncf 
rm -rf vio_async_in96.ngc 
rm -rf vio_async_in96.xco 
rm -rf vio_async_in96.xise 
rm -rf vio_async_in96_flist.txt 
rm -rf vio_async_in96_readme.txt 
rm -rf vio_async_in96_xmdf.tcl 

rm -rf icon4.gise 
rm -rf icon4.ise 
rm -rf icon4.ncf 
rm -rf icon4.ngc 
rm -rf icon4.xco 
rm -rf icon4.xise 
rm -rf icon4_flist.txt 
rm -rf icon4_readme.txt 
rm -rf icon4_xmdf.tcl 

rm -rf ise_flow_results.txt 
rm -rf xlnx_auto_0.ise 
rm -rf ddr2_vhdl.prj 
rm -rf mem_interface_top.syr 
rm -rf ddr2.ngc 
rm -rf ddr2.ngr 
rm -rf ddr2_xst.xrpt 
rm -rf ddr2.bld 
rm -rf ddr2.ngd 
rm -rf ddr2_ngdbuild.xrpt 
rm -rf ddr2_map.map 
rm -rf ddr2_map.mrp 
rm -rf ddr2_map.ngm 
rm -rf ddr2.pcf 
rm -rf ddr2_map.ncd 
rm -rf ddr2_map.xrpt 
rm -rf ddr2_summary.xml 
rm -rf ddr2_usage.xml 
rm -rf ddr2.ncd 
rm -rf ddr2.par 
rm -rf ddr2.xpi 
rm -rf smartpreview.twr 
rm -rf ddr2.ptwx 
rm -rf ddr2.pad 
rm -rf ddr2.unroutes 
rm -rf ddr2_pad.csv 
rm -rf ddr2_pad.txt 
rm -rf ddr2_par.xrpt 
rm -rf ddr2.twx 
rm -rf ddr2.bgn 
rm -rf ddr2.twr 
rm -rf ddr2.drc 
rm -rf ddr2.bit 

# Files and folders generated by create ise
rm -rf test_xdb
rm -rf _xmsgs
rm -rf test.gise
rm -rf test.xise
rm -rf test.ise

# Files and folders generated by ISE through GUI mode
rm -rf _ngo
rm -rf xst
rm -rf ddr2.lso 
rm -rf ddr2.prj 
rm -rf ddr2.xst 
rm -rf ddr2.stx 
rm -rf ddr2.syr 
rm -rf ddr2_prev_built.ngd 
rm -rf test.ntrc_log 
rm -rf ddr2_guide.ncd 
rm -rf ddr2.ut 
rm -rf ddr2.cmd_log 
rm -rf device_usage_statistics.html 
rm -rf ddr2_summary.html 
